---
abstract: 'Add logging to HTTP::Tiny'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Any-For-HTTP-Tiny
requires:
  HTTP::Tiny::Patch::LogAny: 0.01
  Log::Any: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Log-Any-For-HTTP-Tiny
  repository: http://github.com/sharyanto/perl-Log-Any-For-HTTP-Tiny
version: 0.01
